services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.122.0
    container_name: doco-cd
    restart: unless-stopped
    env_file:
      - path: secrets.env
        required: false
    environment:
      TZ: Europe/Berlin
      POLL_CONFIG_FILE: /config/poll-config.yml
      PASS_ENV: "true"
      SELF_UPDATE_ENABLED: "true"
      SELF_UPDATE_STRATEGY: applier
      GITHUB_APP_PRIVATE_KEY_FILE: /run/secrets/doco-cd.private-key.pem
      VIRTUAL_HOST: ${DOCO_CD_HOST:-doco-cd.mv-angelbachtal.de}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${DOCO_CD_HOST:-doco-cd.mv-angelbachtal.de}
    volumes:
      - data:/data
      - ./poll-config.yml:/config/poll-config.yml:ro
      - /opt/doco-cd/doco-cd.private-key.pem:/run/secrets/doco-cd.private-key.pem:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  proxy:
    external: true

volumes:
  data:
    name: doco-cd_data
