- url: https://github.com/mvangelbachtal/app-authentik.git
  reference: main
  interval: 0
- url: https://github.com/mvangelbachtal/app-monitoring.git
  reference: main
  interval: 300
- url: https://github.com/mvangelbachtal/app-nginx-letsencrypt-proxy.git
  reference: main
  interval: 0
- url: https://github.com/mvangelbachtal/app-plik.git
  reference: main
  interval: 300
- url: https://github.com/mvangelbachtal/app-privatebin.git
  reference: main
  interval: 300
- url: https://github.com/mvangelbachtal/app-umami.git
  reference: main
  interval: 300
- url: https://github.com/mvangelbachtal/music-together.git
  reference: main
  interval: 0
- url: https://github.com/mvangelbachtal/app-nextcloud-aio.git
  reference: main
  interval: 0
- url: https://github.com/mvangelbachtal/app-doco-cd.git
  reference: main
  interval: 300
